variables:
  buildConfiguration: 'Release'
jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@4
      displayName: 'Prepare analysis on SonarQube'
      inputs:
        SonarQube: 'SonarCloud'
        projectKey: $(SONARCLOUD_TOKEN)
        projectName: Soulseek.NET
        projectVersion: '$(AssemblyVersion)'
        extraProperties: |
          sonar.organization=jpdillingham
          sonar.branch.name=$(Build.SourceBranchName)
    - powershell: |
        .\build.ps1 -Target "BuildWithCoverageReport"
      displayName: 'Run build script'
    - task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@4
      displayName: 'Run code analysis'
    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: 'out/TestResults/**/*.trx'
      displayName: 'Publish test results'
    - task: PublishCodeCoverageResults@1
      inputs:
        summaryFileLocation: $(Build.SourcesDirectory)/out/Coverage/coverage.cobertura.xml
        reportDirectory: $(Build.SourcesDirectory)/out/CoverageReport
        codecoverageTool: cobertura
      displayName: 'Publish code coverage report'
    - script: |
        %USERPROFILE%\.nuget\packages\codecov\1.1.0\tools\codecov.exe -f $(Build.SourcesDirectory)/out/Coverage/coverage.cobertura.xml -t $(CODECOV_TOKEN)
      displayName: 'Upload coverage to codecov.io'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: './out/Packages/'
        ArtifactName: Packages
        ArtifactType: Container
  - job: Linux
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: ShellScript@2
      inputs:
        scriptPath: build.sh
      displayName: 'Run build script'
    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: 'out/TestResults/**/*.trx'
      displayName: 'Publish test results'