variables:
  buildConfiguration: 'Release'
jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - powershell: |
        .\build.ps1 -Target "BuildAndPublish"
      displayName: 'Run build script'
    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: 'out/TestResults/**/*.trx'
      displayName: 'Publish test results'
    - task: PublishCodeCoverageResults@1
      inputs:
        summaryFileLocation: './out/Coverage/coverage.cobertura.xml'
        reportDirectory: './out/CoverageReport'
        codecoverageTool: cobertura
      displayName: 'Publish code coverage report'
  - job: Linux
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: ShellScript@2
      inputs:
        scriptPath: build.sh
      displayName: 'Run build script'
    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: 'out/TestResults/**/*.trx'
      displayName: 'Publish test results'