version: 2.1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.300-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet tool install --global dotnet-sonarscanner --version 4.6.0
      - run: export PATH="$PATH:$HOME/.dotnet/tools"
      - run: bash ./build/ci.sh